id: PBA4917E7
initial_creation_type: input
source_metadata:
  title: Pilgrimage Series
  language: it
  description: 'Lotsawa House presents the following texts related to pilgrimage (gnas
    skor) and major sacred places (gnas):'
  volume:
    4c1c323dfc0e47429bb12a57f6529fc6:
      title: The Three Types of Pilgrim
      parent: General
    e5915736b87d42a8a75aaf8dbbcc24cc:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Sacred Places
    85aec374bc6a49ab90c5cbf8554b56c2:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Sacred Places
    588b5ca975bf477c932aad3bae574d9b:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Sacred Places
    1d05e8dbaab24ddb8cd73f50f5227473:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Sacred Places
    8edb08b49dc34e608d1bf4e3a5813a5b:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Sacred Places
    94d76552b6d54659951946a6fb446688:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Sacred Places
    2eb00f09f98e44328bb076969511ced8:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Sacred Places
    cc33be93dd5a4104aead4f3da972611d:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    2c70b467d3c94061a6a36960da0ff947:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    315a60273989428a936d446f6e7e069d:
      title: 'Gathering Auspiciousness: A Prayer of Aspiration Made in the Presence
        of the Sacred Mahābodhi Temple and its Imagery, Magadha, Land of the Āryas'
      parent: Sacred Places
    abf8d604afda4910ac1598a89ed253a7:
      title: Guide to Sengchen Namdrak
      parent: Sacred Places
    6acc9ecac3784ea7810d1ce03ff882e5:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    918d46e2f36b4bdf9aaa2b2e4a2df50c:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    586b487e91c44930a328a977507707b3:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    b213fd7841c84acaab34115420d1271d:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    e4983fd2b96a493d8e5bebe78ab09543:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    b7c46401a6e74c4da78b0b54222937f2:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    e67ccaa67c5c443089446171512158b5:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    ecd2fe16d87045928a2bfbfa18b111c2:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Sacred Places
    c624983ef1b04e83a296ef3468b0aee5:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    ed4d021898984bd7a7648fdf89cf680f:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    59b178f3b40342ffa19286fb1c91f2ae:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    ff63c9ee27fe48b39b1f76349a808c92:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Sacred Places
    83210cbff68046efb84ad20d63208532:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Sacred Places
    9ebc0d9d95f54be393a7b199ee1c8fbd:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Sacred Places
    2dcc4cc14613409da5af94f270ca9efb:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    f60d8a835395479087a98dfea34a24eb:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: Sacred Places
    ca77029d68e0461280a1bea0f7174a74:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    f92a97371add4d4f8a2a2ceaa2418dcd:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Sacred Places
    7f31716045dc4cfe89ce8b5801011bf2:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    e8145d3726da4d9b942524afa05b29ff:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Sacred Places
    d4fbf2d42578473788a7899dd8b417e8:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
created_at: '2022-03-01T05:06:14.966934'
last_modified_at: '2022-03-01T05:06:14.966937'
